version: '3'
services:
  nginx:
    ports:
      - '3000:80'

  express-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - FLAG=CTFTC{pragusGANS}
      - MONGO_USER=pass
      - MONGO_PASSWORD=pass1234
      - SESSION_SECRET=tCx32zdUhOFbcQIzyXr6
    command: npm run dev

  mongo:
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pass
      - MONGO_INITDB_ROOT_PASSWORD=pass1234
