version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  express-app:
    container_name: express-app
    build: .
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pass
      - MONGO_INITDB_ROOT_PASSWORD=pass1234
    volumes:
      - mongo_db:/data/db

  redis:
    container_name: redis
    image: redis

volumes:
  mongo_db:
